### ISSUE TITLE
Time data from iTak not parsed

### ISSUE THREAD

**Issue by cursorcl** [snstac/takproto#15]
I have received a data packet from iTak, when converting from the XML received to proto with the api, it shows me
“time data ‘2024-06-05T22:22:31Z+0000’ does not match format ‘%Y-%m-%dT%H:%M:%S.%fZ%z’”

**Comment by brian7704** [comment]
I have the same problem but I'm using WinTAK. I'm working on a fix and if it works I'll submit a PR.

**Comment by ampledata** [comment]
Fixed in v3.0.0
